### PR TITLE
chore: release v1.0.0

### PR DESCRIPTION
**Pull request by hacdias**

### CODE REVIEW

**Review by lidel — APPROVED** [review]
@hacdias  lgtm, let's merge this to tag a stable v1.0.0 with what currently runs in our infra, before we merge and ship other things.

I've created milestones for few next minor versions:
https://github.com/ipfs/rainbow/milestones
feel free to adjust / merge them.

**Comment by hacdias** [comment]
@lidel there's some issue with the Docker release process, as we're not getting a `latest`,nor `v1.0.0` tag released. The Docker workflow did not get dispatched for the tag, even though we have it set in the workflow. I wonder if this is not releted to the way the UCI creates a tag: I think it uses GitHub's API and maybe that doesn't trigger the `on push tag`.

In the meanwhile, I updated the Workflow to allow it to be manually triggered, but since it wasn't so in the release tag, I can't really trigger it in the past.

I will take a better look Monday.

**Comment by galargh** [comment]
@hacdias We can fix this! This happens because events created by the default GitHub Token do not trigger workflows. I do not like this design choice personally, but we can work around it.

First, you can add the following trigger to the docker release workflow:
https://github.com/ipfs/bifrost-gateway/blob/0bb1a904cc4af6c0b5e3398a67f320c1eec383a1/.github/workflows/docker-image.yml#L11-L14

It will trigger whenever there is a run of the Releaser workflow.

Then, you can add the following job:
https://github.com/ipfs/bifrost-gateway/blob/0bb1a904cc4af6c0b5e3398a67f320c1eec383a1/.github/workflows/docker-image.yml#L24-L42

The job checks details about the release, if it happened, what ref it used, etc.

Remember to make the docker release job depend on the newly added one like so:
https://github.com/ipfs/bifrost-gateway/blob/0bb1a904cc4af6c0b5e3398a67f320c1eec383a1/.github/workflows/docker-image.yml#L44

Finally, use the retrieved ref in the checkout:
https://github.com/ipfs/bifrost-gateway/blob/0bb1a904cc4af6c0b5e3398a67f320c1eec383a1/.github/workflows/docker-image.yml#L51-L54

**Comment by hacdias** [comment]
@galargh thanks for the speedy answer. I will do this tomorrow and try it out when releasing v1.1.0 😄 If all goes smoothly, I will implement the same changes in `ipfs/someguy`.

**Comment by galargh** [comment]
Yes! Using a PAT to create releases would circumvent that issue. We can implement PAT support for the releaser workflow next month if you wanted us to.

We definitely could create a fine-grained @web3-bot token which has write access to Interplanetary Shipyard repositories only, too.

**Comment by hacdias** [comment]
@galargh I think that would be great. If it's only happening next month, I will go ahead and merge #122 for now.

**Comment by galargh** [comment]
Yes, unfortunately, we have already reached the work quota this month and were asked not to go beyond. But we'll get to it first thing in May 💪

**Pull request merged**
