### PR TITLE
feat(ci): build and publish staging docker images

### LINKED ISSUE #78: Automated Docker builds for `main` and `staging` branches
We already have Docker images for the `main` branch. The idea is to have also `staging` branch that produces Docker builds, allowing for more experimentation.

### PR DESCRIPTION
**Pull request by hacdias**
Closes #78.

### CODE REVIEW

**Comment by hacdias** [comment]
@aschmahmann do you know why we use our own script to generate the Docker labels instead of something simpler (e.g. https://github.com/docker/metadata-action)?

**Comment by lidel** [comment]
The way we generate labels comes from go-ipfs and predates Github Actions.

We could refactor it, as long a new method gives us the same level of flexibility around label filenames, but I'd  say it is better to use the same setup everywhere (kubo/rainbow/someguy) right now, and spend time elsewhere. Refactor can be done after more pressing IPDX work lands this year.

**Review by lidel — APPROVED** [review]
Lgtm, ported some user-friendly Docker docs.

**Comment by lidel** [comment]
@ns4plabs  @aschmahmann  fyi I've created `staging` branch, and confirmed images for that branch are build correctly:

https://github.com/ipfs/rainbow/actions/runs/7865229424 produced [`ghcr.io/ipfs/rainbow:staging-2024-02-11-018e2c2`](https://github.com/ipfs/rainbow/pkgs/container/rainbow/177529048?tag=staging-2024-02-11-018e2c2), all tags can be listed at https://github.com/ipfs/rainbow/pkgs/container/rainbow/


You can use this setup for deterministic builds that we then can run as staging experiments.

**Pull request merged**
